name: Build React App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set env var from GitHub Environment
        run: echo "REACT_APP_LAUNCH_DATE=${{ vars.LAUNCH_DATE }}" >> .env

      - name: Build
        run: npm run build

      # Optional: deploy to GitHub Pages, Netlify, etc.
