name: Build React App

on:
  push:
    branches: [main]  # Trigger on push to main branch

  workflow_dispatch:   # ✅ Manual trigger support
    inputs:
      launch_date:
        description: 'Override launch date (YYYY-MM-DD)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod  # Use GitHub Environment variables

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set environment variable from input or GitHub environment
        run: |
          LAUNCH_DATE=${{ github.event.inputs.launch_date || vars.LAUNCH_DATE }}
          echo "REACT_APP_LAUNCH_DATE=$LAUNCH_DATE" >> .env
          echo "Using launch date: $LAUNCH_DATE"
          cat .env
      
